# Generated by Django 6.1 on 2026-08-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="verification_token",
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
