# Generated by Django 6.1 on 2026-08-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("overview", models.TextField(blank=True)),
                (
                    "poster_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "backdrop_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("release_date", models.DateField(blank=True, null=True)),
                ("runtime", models.IntegerField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=10, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("genre", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
