# Generated by Django 6.1 on 2026-09-04 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_booking_verification_token'),
        ('cinemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('POPCORN', 'Popcorn'), ('BEVERAGE', 'Beverage'), ('SNACK', 'Snack'), ('COMBO', 'Combo')], default='SNACK', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.URLField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('theatre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snacks', to='cinemas.theatre')),
            ],
        ),
        migrations.CreateModel(
            name='BookingSnack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_snacks', to='bookings.booking')),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='snacks.snack')),
            ],
        ),
    ]
