# Generated by Django 6.1 on 2026-09-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snacks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snack",
            name="image",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
