# Generated by Django 6.1 on 2026-08-20 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinemas", "0001_initial"),
        ("shows", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShowSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("HELD", "Held"),
                            ("BOOKED", "Booked"),
                        ],
                        default="AVAILABLE",
                        max_length=10,
                    ),
                ),
                ("hold_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="show_seats",
                        to="cinemas.seat",
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="show_seats",
                        to="shows.show",
                    ),
                ),
            ],
            options={
                "unique_together": {("show", "seat")},
            },
        ),
    ]
